
---
root: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 9 # It's silly they go by ECMA "version numbers" like this
  sourceType: module
plugins:
  - react
settings:
  react:
    version: detect
env:
  browser: true
  es6: true
  jest: true
  node: true
globals:
  DEFINED_APP_VERSION: true
  DEFINED_GIT_REVISION: true
rules:
  prefer-const: error
  rest-spread-spacing:
    - error
    - never
  semi:
    - error
    - never
